### ISSUE TITLE
로그인 인가 조건을 바꿔야 할 것 같습니다.

### ISSUE THREAD

**Issue by Im-Siyoun** [Jeong-Rae/sejong-auth-delegator#2]
세종대학교 API가 업데이트를 했는지, 로그인 인가처리를 할 때 로그인에 성공했더라도 responseBody에 '접속자 정보'가 포함되지 않습니다.
따라서 조건을 다음과 같이 바꿀 것을 제안드립니다.

if (responseBody.includes("접속자 정보")) {
    return true;
}

if (!responseBody.includes("올바르지 않습니다")) {
    return true;
}
혹은
if (responseBody.includes("대양휴머니티칼리지") {
    return true;
}

**Comment by Jeong-Rae** [comment]
확인했습니다.
성공/실패시 반환되는 HTML 형식이 변경된 것 같습니다.
이에 맞춰 더 고유한 실패 값으로 인증 여부를 변경하였습니다.

추가적으로 LoginRequestDTO 사용시 create 메서드를 이용한 static 빌더 패턴방식만이 가능한 상태에서, class 자체를 export로 받아 사용할 수 있도록 수정하였습니다.

감사합니다
